### PR TITLE
Uppdate dispatch interval on admin node

### PR DESCRIPTION
**Pull request by NgoniChoga**

### CODE REVIEW

**Comment by smarquard** [comment]
Looking at upstream 14.x, it seems this config should be in https://github.com/opencast/opencast/blob/r/14.x/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg ?

Please align our config files with the upstream versions, as it's misleading if we carry over comments or settings from earlier versions that are no longer correct.

**Comment by NgoniChoga** [comment]
> Looking at upstream 14.x, it seems this config should be in https://github.com/opencast/opencast/blob/r/14.x/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg ?
> 
> Please align our config files with the upstream versions, as it's misleading if we carry over comments or settings from earlier versions that are no longer correct.

@smarquard Updated

**Comment by smarquard** [comment]
> > Looking at upstream 14.x, it seems this config should be in https://github.com/opencast/opencast/blob/r/14.x/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg ?
> > Please align our config files with the upstream versions, as it's misleading if we carry over comments or settings from earlier versions that are no longer correct.
> 
> @smarquard Updated

Yes but this still is a change to a dfiferent file? In 14.x this config appears to be in [org.opencastproject.serviceregistry.impl.JobDispatcher.cfg](https://github.com/opencast/opencast/blob/r/14.x/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg) and this PR updates [org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg](https://github.com/cilt-uct/oc-scripts/pull/84/files#diff-8977e570fccb2a4eb7b9348cb7076eff25ae0e1504ba3b4d8736eb04547543eb)

**Comment by NgoniChoga** [comment]
> > > Looking at upstream 14.x, it seems this config should be in https://github.com/opencast/opencast/blob/r/14.x/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg ?
> > > Please align our config files with the upstream versions, as it's misleading if we carry over comments or settings from earlier versions that are no longer correct.
> > 
> > 
> > @smarquard Updated
> 
> Yes but this still is a change to a dfiferent file? In 14.x this config appears to be in [org.opencastproject.serviceregistry.impl.JobDispatcher.cfg](https://github.com/opencast/opencast/blob/r/14.x/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg) and this PR updates [org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg](https://github.com/cilt-uct/oc-scripts/pull/84/files#diff-8977e570fccb2a4eb7b9348cb7076eff25ae0e1504ba3b4d8736eb04547543eb)

Pushed changes, thanks.

**Review by smarquard — APPROVED** [review]
Looks good

**Comment by smarquard** [comment]
At some point you'd want a matching one for srvubuopc001 (production)

**Review by npmali — APPROVED** [review]

**Pull request merged**
